name: bimRESOLVE
favicon: null
layout_spectrum: 0.6196416928432882
typography_spectrum: 0.06279864488169551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2726807671133429
  lightness: 0.3396086774300784
  saturation: 0.055974071845412254
  rhythmicContrast: 0.21879724645987153
purpose: []
